"""Test utility to write meeting (period) attendance codes to students via the PowerSchool API, so the daily attendance conversion script can be tested without hand-entering codes.

Given a student number, an attendance code, and a number of periods, this looks up the student's actual scheduled sections for the target date
and writes that many periods of the given code, starting from their earliest period of the day. Intended to be pointed at a TEST server only.

Needs oracledb: pip install oracledb --upgrade
Needs the ACME PowerSchool library from https://easyregpro.com/acme.php
"""

import datetime
import json
import os

import acme_powerschool
import oracledb

# PowerSchool API credentials - deliberately using the TEST/RES server variables rather than PROD, since this script writes fake attendance data
D118_API_ID = os.environ.get("POWERSCHOOL_API_ID_2")
D118_API_SECRET = os.environ.get("POWERSCHOOL_API_SECRET_2")

# Database credentials - again pointing at the test server
DB_UN = os.environ.get('POWERSCHOOL_READ_USER')
DB_PW = os.environ.get('POWERSCHOOL_DB_PASSWORD')
DB_CS = os.environ.get('POWERSCHOOL_RES_DB')
API_URL = os.environ.get('POWERSCHOOL_RES_URL')

# Configuration
SCHOOL_ID = 5  # The school ID the test students belong to, used for calendar/term/attendance code lookups
TARGET_DATE = datetime.datetime.now().replace(hour=0, minute=0, second=0, microsecond=0) - datetime.timedelta(days=2)  # The date to write the test meeting attendance for. Change this to backdate test data, e.g. datetime.datetime(2026, 9, 2)
ATT_COMMENT = 'Test data generated by the meeting attendance test utility'  # Comment written into every generated record so fake data is easy to spot and clean up later

# The list of test attendance to write. Each entry is one student getting one code applied to some number of their scheduled periods.
# 'student_number' is the visible student number, 'code' is the meeting attendance code, 'periods' is how many of their periods get that code (starting from their earliest period of the day).
TEST_ASSIGNMENTS = [
    {'student_number': 222506, 'code': 'OSS', 'periods': 4},
    {'student_number': 224564, 'code': 'CV', 'periods': 7},
    {'student_number': 221187, 'code': 'PEL', 'periods': 7},
    {'student_number': 224389, 'code': 'UH', 'periods': 8},
]

DRY_RUN = True  # If True, will not write anything, just log the payloads that would be sent

print(f'DBUG: DB Username: {DB_UN} | DB Server: {DB_CS} | API URL: {API_URL}')
print(f'DBUG: Dry Run is set to {DRY_RUN}, target date is {TARGET_DATE.strftime("%Y-%m-%d")}')

def get_student_id(cur: any, student_number: int) -> int | None:
    """Get the internal student ID (STUDENTS.ID) for a given visible student number, or None if the student cannot be found."""
    cur.execute('SELECT id, lastfirst FROM students WHERE student_number = :stunum', stunum=student_number)
    result = cur.fetchone()
    if result is not None:
        print(f'DBUG: Found student ID {result[0]} ({result[1]}) for student number {student_number}')
        print(f'DBUG: Found student ID {result[0]} ({result[1]}) for student number {student_number}', file=log)
        return result[0]
    else:
        print(f'ERROR: Could not find a student with student number {student_number}')
        print(f'ERROR: Could not find a student with student number {student_number}', file=log)
        return None

def get_calendar_day_info(cur: any, school_id: int) -> tuple | None:
    """Get the calendar day ID, bell schedule ID, and cycle day letter for the target date, or None if the date is not a school day at this building."""
    # calendar_day holds one row per date per school, and links out to both the bell schedule (which defines period start/end times) and the cycle day (which defines which sections meet)
    cur.execute('SELECT cd.id, cd.bell_schedule_id, cyd.letter, cd.insession FROM calendar_day cd \
                LEFT JOIN cycle_day cyd ON cd.cycle_day_id = cyd.id \
                WHERE cd.schoolid = :school AND cd.date_value = :target', school=school_id, target=TARGET_DATE)
    result = cur.fetchone()
    if result is None:
        print(f'ERROR: No calendar day found at building {school_id} for {TARGET_DATE.strftime("%Y-%m-%d")}, it is likely a weekend or outside the school year')
        print(f'ERROR: No calendar day found at building {school_id} for {TARGET_DATE.strftime("%Y-%m-%d")}, it is likely a weekend or outside the school year', file=log)
        return None

    calendar_day_id = result[0]
    bell_schedule_id = result[1]
    cycle_day_letter = result[2]
    in_session = result[3]

    if in_session != 1:  # warn but continue, since you may deliberately want to test what happens on a non-session day
        print(f'WARN: {TARGET_DATE.strftime("%Y-%m-%d")} is marked as not in session at building {school_id}, continuing anyway')
        print(f'WARN: {TARGET_DATE.strftime("%Y-%m-%d")} is marked as not in session at building {school_id}, continuing anyway', file=log)

    print(f'DBUG: Calendar day ID {calendar_day_id}, bell schedule ID {bell_schedule_id}, cycle day letter {cycle_day_letter} for {TARGET_DATE.strftime("%Y-%m-%d")}')
    print(f'DBUG: Calendar day ID {calendar_day_id}, bell schedule ID {bell_schedule_id}, cycle day letter {cycle_day_letter} for {TARGET_DATE.strftime("%Y-%m-%d")}', file=log)
    return (calendar_day_id, bell_schedule_id, cycle_day_letter)

def get_year_id(cur: any, school_id: int) -> int | None:
    """Get the year ID for the target date at a given school, or None if the date falls outside any defined year."""
    cur.execute('SELECT yearid FROM terms WHERE isyearrec = 1 AND schoolid = :school AND :target BETWEEN firstday AND lastday', school=school_id, target=TARGET_DATE)
    result = cur.fetchone()
    if result is not None:
        print(f'DBUG: Found year ID {result[0]} for building {school_id} on {TARGET_DATE.strftime("%Y-%m-%d")}')
        print(f'DBUG: Found year ID {result[0]} for building {school_id} on {TARGET_DATE.strftime("%Y-%m-%d")}', file=log)
        return result[0]
    else:
        print(f'ERROR: Could not find a year ID at building {school_id} for {TARGET_DATE.strftime("%Y-%m-%d")}')
        print(f'ERROR: Could not find a year ID at building {school_id} for {TARGET_DATE.strftime("%Y-%m-%d")}', file=log)
        return None

def get_attendance_code_id(cur: any, school_id: int, code: str) -> int | None:
    """Get the attendance code ID for a given attendance code and school on the target date, or None if it cannot be found."""
    cur.execute('SELECT ac.id FROM attendance_code ac LEFT JOIN terms t ON ac.yearid = t.yearid \
                WHERE ac.att_code = :code AND ac.schoolid = :school AND t.isyearrec = 1 AND t.schoolid = :school \
                AND :target BETWEEN t.firstday AND t.lastday', code=code, school=school_id, target=TARGET_DATE)
    result = cur.fetchone()
    if result is not None:
        print(f'DBUG: Found attendance code ID {result[0]} for code {code} at building {school_id}')
        print(f'DBUG: Found attendance code ID {result[0]} for code {code} at building {school_id}', file=log)
        return result[0]
    else:
        print(f'ERROR: Could not find the {code} attendance code at building {school_id} for {TARGET_DATE.strftime("%Y-%m-%d")}')
        print(f'ERROR: Could not find the {code} attendance code at building {school_id} for {TARGET_DATE.strftime("%Y-%m-%d")}', file=log)
        return None

def get_student_schedule(cur: any, student_id: int, school_id: int, bell_schedule_id: int, cycle_day_letter: str) -> list:
    """Get the student's scheduled meetings for the target date as a list of dicts with the ccid, periodid, period number, and period start/end times the meeting attendance API requires."""
    meetings = []  # list of dicts, one per scheduled period the student has on the target date, ordered earliest period first
    try:
        # cc holds the student's section enrollments, section_meeting says which cycle days and periods each section meets on,
        # period maps the period number to the internal period ID, and bell_schedule_items gives the start/end times for that period under the day's bell schedule
        cur.execute('SELECT cc.id, sm.period_number, p.id, bsi.start_time, bsi.end_time FROM cc \
                    INNER JOIN section_meeting sm ON cc.sectionid = sm.sectionid \
                    INNER JOIN period p ON sm.period_number = p.period_number AND p.schoolid = sm.schoolid AND p.year_id = sm.year_id \
                    INNER JOIN bell_schedule_items bsi ON bsi.period_id = p.id AND bsi.bell_schedule_id = :bellsched \
                    WHERE cc.studentid = :stuid AND cc.schoolid = :school AND sm.cycle_day_letter = :cycleletter \
                    AND :target BETWEEN cc.dateenrolled AND cc.dateleft \
                    ORDER BY sm.period_number', stuid=student_id, school=school_id, bellsched=bell_schedule_id, cycleletter=cycle_day_letter, target=TARGET_DATE)
        results = cur.fetchall()

        seen_periods = set()  # track which period numbers we've already taken, so a student double-scheduled in one period only gets one attendance record for it
        for row in results:
            period_number = row[1]
            if period_number in seen_periods:  # skip duplicate periods, since writing two meeting records for the same period would double-count against the daily thresholds
                print(f'WARN: Student ID {student_id} has more than one section in period {period_number}, only using the first one found')
                print(f'WARN: Student ID {student_id} has more than one section in period {period_number}, only using the first one found', file=log)
                continue
            seen_periods.add(period_number)
            meetings.append({'ccid': row[0], 'period_number': period_number, 'periodid': row[2], 'start_time': row[3], 'end_time': row[4]})

        print(f'DBUG: Found {len(meetings)} scheduled period(s) for student ID {student_id} on {TARGET_DATE.strftime("%Y-%m-%d")}: periods {[m["period_number"] for m in meetings]}')
        print(f'DBUG: Found {len(meetings)} scheduled period(s) for student ID {student_id} on {TARGET_DATE.strftime("%Y-%m-%d")}: periods {[m["period_number"] for m in meetings]}', file=log)
    except Exception as er:
        print(f'ERROR while looking up the schedule for student ID {student_id}: {er}')
        print(f'ERROR while looking up the schedule for student ID {student_id}: {er}', file=log)
    return meetings

def show_existing_meeting_attendance(cur: any, student_id: int, school_id: int) -> None:
    """Print the student's current meeting attendance for the target date, useful for confirming before and after what the test data actually did."""
    try:
        cur.execute('SELECT att_code, count(*) as count FROM pssis_attendance_meeting \
                    WHERE studentid = :stuid AND schoolid = :school AND att_date = :target \
                    GROUP BY att_code ORDER BY att_code', stuid=student_id, school=school_id, target=TARGET_DATE)
        results = cur.fetchall()
        if results:
            code_summary = ', '.join(f'{count} x {code}' for code, count in results)  # build a readable summary like "3 x UP, 5 x P"
            print(f'INFO: Student ID {student_id} currently has meeting attendance of: {code_summary}')
            print(f'INFO: Student ID {student_id} currently has meeting attendance of: {code_summary}', file=log)
        else:
            print(f'INFO: Student ID {student_id} currently has no meeting attendance records for {TARGET_DATE.strftime("%Y-%m-%d")}')
            print(f'INFO: Student ID {student_id} currently has no meeting attendance records for {TARGET_DATE.strftime("%Y-%m-%d")}', file=log)
    except Exception as er:
        print(f'ERROR while reading existing meeting attendance for student ID {student_id}: {er}')
        print(f'ERROR while reading existing meeting attendance for student ID {student_id}: {er}', file=log)

def get_student_scheduled_period_count(cur: any, student_id: int, school_id: int, cycle_day_letter: str) -> int | None:
    """Get how many distinct attendance-taking periods a student is actually scheduled for on the current TODAY date, so students with partial schedules aren't compared against a full-day period count."""
    try:
        # count distinct period numbers rather than sections, since a student double-scheduled in one period should still only count that period once
        # exclude_ada = 0 filters out sections that don't count toward attendance (study halls and similar), which would otherwise inflate the expected period count
        cur.execute('SELECT COUNT(DISTINCT sm.period_number) FROM cc \
                    INNER JOIN section_meeting sm ON cc.sectionid = sm.sectionid \
                    INNER JOIN sections s ON cc.sectionid = s.id \
                    WHERE cc.studentid = :stuid AND cc.schoolid = :school AND sm.cycle_day_letter = :cycleletter \
                    AND :today BETWEEN cc.dateenrolled AND cc.dateleft AND s.exclude_ada = 0', stuid=student_id, school=school_id, cycleletter=cycle_day_letter, today=TARGET_DATE)
        result = cur.fetchone()
        if result is not None and result[0] > 0:
            return result[0]
        else:
            print(f'WARN: Student ID {student_id} has no scheduled attendance-taking periods at building {school_id} on {TARGET_DATE}')
            print(f'WARN: Student ID {student_id} has no scheduled attendance-taking periods at building {school_id} on {TARGET_DATE}', file=log)
            return None
    except Exception as er:
        print(f'ERROR while counting scheduled periods for student ID {student_id}: {er}')
        print(f'ERROR while counting scheduled periods for student ID {student_id}: {er}', file=log)
        return None

def write_meeting_attendance(ps: any, student_id: int, school_id: int, year_id: int, calendar_day_id: int, attendance_code_id: int, meetings: list) -> None:
    """Write one meeting attendance record per supplied meeting via a single API call, since the endpoint accepts multiple records as long as they are all for one student on one day."""
    records = []  # build up one record per period, all bundled into a single POST
    for meeting in meetings:
        records.append({
            "name": "ATTENDANCE",
            "tables": {
                "attendance": {
                    "attendance_codeid": str(attendance_code_id),
                    "calendar_dayid": str(calendar_day_id),
                    "schoolid": str(school_id),
                    "yearid": str(year_id),
                    "studentid": str(student_id),
                    "ccid": str(meeting['ccid']),  # the class enrollment record this period's attendance is attached to
                    "periodid": str(meeting['periodid']),  # the internal period ID, not the period number
                    "att_mode_code": "ATT_ModeMeeting",
                    "att_comment": ATT_COMMENT,
                    "start_time": int(meeting['start_time']),  # seconds since midnight, taken straight from the bell schedule for this period
                    "end_time": int(meeting['end_time']),  # seconds since midnight, taken straight from the bell schedule for this period
                    "att_date": TARGET_DATE.strftime('%Y-%m-%d'),
                    "programid": "0"
                }
            }
        })

    data = {"name": "ATTENDANCE", "record": records}

    if DRY_RUN:
        print(f'WARN: Dry run enabled, would have posted {len(records)} meeting attendance record(s) for student ID {student_id}')
        print(f'WARN: Dry run enabled, would have posted {len(records)} meeting attendance record(s) for student ID {student_id}', file=log)
        print(f'DBUG: Payload that would be sent: {json.dumps(data)}')
        print(f'DBUG: Payload that would be sent: {json.dumps(data)}', file=log)
        return

    try:
        result = ps.post('ws/attendance/meeting_interval', data=json.dumps(data))
        if result.status_code == 200:
            print(f'INFO: Successfully wrote {len(records)} meeting attendance record(s) for student ID {student_id}')
            print(f'INFO: Successfully wrote {len(records)} meeting attendance record(s) for student ID {student_id}', file=log)
        else:
            print(f'ERROR: Failed to write meeting attendance for student ID {student_id}: {result} {result.text}')
            print(f'ERROR: Failed to write meeting attendance for student ID {student_id}: {result} {result.text}', file=log)
    except Exception as er:
        print(f'ERROR while writing meeting attendance for student ID {student_id}: {er}')
        print(f'ERROR while writing meeting attendance for student ID {student_id}: {er}', file=log)

def process_assignment(cur: any, ps: any, assignment: dict, school_id: int, year_id: int, calendar_day_id: int, bell_schedule_id: int, cycle_day_letter: str) -> None:
    """Process one entry from TEST_ASSIGNMENTS, resolving the student and their schedule then writing the requested number of periods of the requested code."""
    student_number = assignment.get('student_number')
    att_code = assignment.get('code')
    num_periods = assignment.get('periods')

    print(f'INFO: Processing assignment of {num_periods} period(s) of code {att_code} for student number {student_number}')
    print(f'INFO: Processing assignment of {num_periods} period(s) of code {att_code} for student number {student_number}', file=log)

    student_id = get_student_id(cur, student_number)
    if student_id is None:
        return  # get_student_id already logged the reason, so just move on to the next assignment

    attendance_code_id = get_attendance_code_id(cur, school_id, att_code)
    if attendance_code_id is None:
        return  # get_attendance_code_id already logged the reason

    show_existing_meeting_attendance(cur, student_id, school_id)  # log what they had before, so the log shows the before/after of this run

    meetings = get_student_schedule(cur, student_id, school_id, bell_schedule_id, cycle_day_letter)
    if not meetings:
        print(f'ERROR: Student number {student_number} has no scheduled sections on {TARGET_DATE.strftime("%Y-%m-%d")}, cannot write meeting attendance')
        print(f'ERROR: Student number {student_number} has no scheduled sections on {TARGET_DATE.strftime("%Y-%m-%d")}, cannot write meeting attendance', file=log)
        return

    if num_periods > len(meetings):  # asking for more periods than they actually have scheduled, so cap it and warn rather than silently writing fewer
        print(f'WARN: Requested {num_periods} period(s) for student number {student_number} but they only have {len(meetings)} scheduled, using all {len(meetings)}')
        print(f'WARN: Requested {num_periods} period(s) for student number {student_number} but they only have {len(meetings)} scheduled, using all {len(meetings)}', file=log)

    target_meetings = meetings[:num_periods]  # take the first N periods of their day, since the list is already sorted by period number
    print(f'DBUG: Writing code {att_code} to period(s) {[m["period_number"] for m in target_meetings]} for student number {student_number}')
    print(f'DBUG: Writing code {att_code} to period(s) {[m["period_number"] for m in target_meetings]} for student number {student_number}', file=log)

    write_meeting_attendance(ps, student_id, school_id, year_id, calendar_day_id, attendance_code_id, target_meetings)

if __name__ == '__main__':
    with open('TestMeetingAttendanceLog.txt', 'w') as log:
        startTime = datetime.datetime.now()
        startTime = startTime.strftime('%H:%M:%S')
        print(f'Execution started at {startTime}')
        print(f'Execution started at {startTime}', file=log)

        try:
            with oracledb.connect(user=DB_UN, password=DB_PW, dsn=DB_CS) as con:
                with con.cursor() as cur:
                    print('INFO: Database connection established')
                    print('INFO: Database connection established', file=log)
                    ps = acme_powerschool.api(API_URL, client_id=D118_API_ID, client_secret=D118_API_SECRET)  # start the PowerSchool API session

                    # resolve the day-level values once, since every assignment below shares the same date and building
                    calendar_info = get_calendar_day_info(cur, SCHOOL_ID)
                    if calendar_info is None:
                        print('ERROR: Could not resolve the calendar day, cannot continue')
                        print('ERROR: Could not resolve the calendar day, cannot continue', file=log)
                        exit(1)
                    calendar_day_id, bell_schedule_id, cycle_day_letter = calendar_info

                    year_id = get_year_id(cur, SCHOOL_ID)
                    if year_id is None:
                        print('ERROR: Could not resolve the year ID, cannot continue')
                        print('ERROR: Could not resolve the year ID, cannot continue', file=log)
                        exit(1)

                    # work through each test assignment one at a time, each one is independent so a failure on one does not stop the others
                    for assignment in TEST_ASSIGNMENTS:
                        process_assignment(cur, ps, assignment, SCHOOL_ID, year_id, calendar_day_id, bell_schedule_id, cycle_day_letter)

        except Exception as er:
            print(f'ERROR while connecting to the database: {er}')
            print(f'ERROR while connecting to the database: {er}', file=log)
            exit(1)

        endTime = datetime.datetime.now()
        endTime = endTime.strftime('%H:%M:%S')
        print(f'Execution ended at {endTime}')
        print(f'Execution ended at {endTime}', file=log)
